### ISSUE TITLE
can you create cdn link for this

### ISSUE THREAD

**Issue by satra2806** [dc-js/dc.datatables.js#18]
Hi Please create CDN @gordonwoodhull

**Comment by gordonwoodhull** [comment]
Hi @satra2806, my understanding is that traditional CDNs are obsolete for JS, and services based on NPM packages and ES6 modules are the way forward.

Accordingly, you can use unpkg.com

https://unpkg.com/dc.datatables/dc.datatables.js

or jsdelivr.net

https://cdn.jsdelivr.net/npm/dc.datatables/dc.datatables.js

Please let me know if this is insufficient.
