### ISSUE TITLE
Enabling default styling

### ISSUE THREAD

**Issue by jackcrymble** [dc-js/dc.datatables.js#2]
I have got dc.datatables working within my project, however it appears that there is no default styling being applied? Is this on purpose? I can see in the web folder, you have copied the 'jquery.datatables.css' file from the datatables.net-dt package. Is this the recommended way to apply styling to the dc.datatable as opposed to having a css file within the dc.datatables package which is applied by default but can be overridden?

![datatables_no_styling](https://user-images.githubusercontent.com/11898127/46665506-f7b5a680-cbbb-11e8-8bdb-7c4299288e94.png)
This is what the datatable looks like with no styling (created using titanic dataset).

**Comment by jackcrymble** [comment]
Okay, @gordonwoodhull! 

I'll keep looking into this for my project and see if I can get somewhere. I'm somewhat new to front end development but will update if anything useful comes from my efforts.

**Comment by gordonwoodhull** [comment]
As far as I know, including the CSS from all dependencies is the way to go - but maybe there is something automatic that Angular or another build system can help with.

**Comment by jackcrymble** [comment]
Importing the jquery dataTables css file into my styles.scss seems to do the trick for applying some styling!

`@import '~datatables/media/css/jquery.dataTables.css';
`

What do you plan for the dc.datatables.css file? Will it remain blank or will some form of styling be added in here at a later date?

Thanks for your help and quick replies!

**Comment by gordonwoodhull** [comment]
That's great!

I added `dc.datatables.css` out of habit but it is unlikely to be needed, since this library does not generate html directly. It should probably be removed, especially if it causes confusion.

I'll close this issue for now - we can reopen if we discover a better way to specify transitive css dependencies.
